@startuml
title Diagrama de classes - N-body

skinparam classAttributeIconSize 0
left to right direction

package solution {
  class Main {
    + {static} main(args: String[]): void
  }

  class MainCentral {
    + {static} main(args: String[]): void
  }

  class MainPlanetary {
    + {static} main(args: String[]): void
  }

  class MainChoreography {
    + {static} main(args: String[]): void
  }

  class NBodySimulator {
    - timeStep: double
    - pauseTime: int
    - trace: boolean
    - universe: Universe
    --
    + NBodySimulator(universe: Universe, dt: double, pt: int, doTrace: boolean)
    + simulate(): void
    - createCanvas(): void
    - drawUniverse(): void
  }

  class Universe {
    - numBodies: int
    - radius: double
    - bodies: Body[]
    --
    + Universe(bodies: Body[], radius: double)
    + Universe(fname: String)
    + getNumBodies(): int
    + getRadius(): double
    + getBodyPosition(i: int): Vector
    + update(dt: double): void
  }

  class Body {
    - r: Vector
    - v: Vector
    - mass: double
    - G: double
    --
    + Body(r: Vector, v: Vector, mass: double)
    + Body(r: Vector, v: Vector, mass: double, G: double)
    + move(f: Vector, dt: double): void
    + forceFrom(b: Body): Vector
    + getPosition(): Vector
    + toString(): String
  }

  class Vector {
    - n: int
    - data: double[]
    --
    + Vector(n: int)
    + Vector(data: double[])
    + length(): int
    + dot(that: Vector): double
    + magnitude(): double
    + distanceTo(that: Vector): double
    + plus(that: Vector): Vector
    + minus(that: Vector): Vector
    + cartesian(i: int): double
    + times(factor: double): Vector
    + scale(factor: double): Vector
    + direction(): Vector
    + toString(): String
  }

  class UniverseFactory {
    + {static} makeCentralConfiguration(numBodies: int, angleVelPos: double): Universe
    + {static} makePlanetaryConfiguration(numPlanets: int): Universe
    + {static} makeChoreography(nchoreography: int): Universe
    - {static} randomBetween(minValue: double, maxValue: double): double
  }

  class StdDraw

  NBodySimulator --> "1" Universe : universe
  Universe --> "0..*" Body : bodies
  Body --> "2" Vector : r, v

  NBodySimulator ..> StdDraw : dibuixa
  UniverseFactory ..> Universe : crea
  UniverseFactory ..> Body : crea
  UniverseFactory ..> Vector : crea

  Main ..> Universe : crea des de fitxer
  Main ..> NBodySimulator : crea
  MainCentral ..> UniverseFactory : utilitza
  MainCentral ..> NBodySimulator : crea
  MainPlanetary ..> UniverseFactory : utilitza
  MainPlanetary ..> NBodySimulator : crea
  MainChoreography ..> UniverseFactory : utilitza
  MainChoreography ..> NBodySimulator : crea
}
@enduml
